package com.example.amasamya.utils

import com.example.amasamya.db.ElementIssue

object TestScriptExporter {

    enum class TestFramework {
        JETPACK_COMPOSE,
        ESPRESSO
    }

    /**
     * Generates a complete, runnable test class file for a full list of audit issues.
     */
    fun generateFullTestClass(
        sessionName: String,
        packageName: String,
        issues: List<ElementIssue>,
        framework: TestFramework
    ): String {
        return when (framework) {
            TestFramework.JETPACK_COMPOSE -> generateComposeTestClass(sessionName, packageName, issues)
            TestFramework.ESPRESSO -> generateEspressoTestClass(sessionName, packageName, issues)
        }
    }

    /**
     * Generates an individual test snippet for a single issue.
     */
    fun generateSingleIssueSnippet(issue: ElementIssue, framework: TestFramework): String {
        return when (framework) {
            TestFramework.JETPACK_COMPOSE -> generateComposeSnippet(issue)
            TestFramework.ESPRESSO -> generateEspressoSnippet(issue)
        }
    }

    private fun generateComposeTestClass(
        sessionName: String,
        packageName: String,
        issues: List<ElementIssue>
    ): String {
        val className = sanitizeIdentifier(sessionName) + "AccessibilityTest"
        val sb = StringBuilder()
        sb.append("package ").append(packageName.ifEmpty { "com.example.app" }).append(".accessibility\n\n")
        sb.append("import androidx.compose.ui.test.junit4.createComposeRule\n")
        sb.append("import androidx.compose.ui.test.onNodeWithContentDescription\n")
        sb.append("import androidx.compose.ui.test.onNodeWithText\n")
        sb.append("import androidx.compose.ui.test.assertIsDisplayed\n")
        sb.append("import androidx.compose.ui.test.assertTouchTargetMinSize\n")
        sb.append("import androidx.compose.ui.unit.dp\n")
        sb.append("import org.junit.Rule\n")
        sb.append("import org.junit.Test\n\n")
        sb.append("/**\n")
        sb.append(" * Automated Compose Accessibility Regression Test\n")
        sb.append(" * Generated by AMASAMYA Accessibility Engine for session: ").append(sessionName).append("\n")
        sb.append(" */\n")
        sb.append("class ").append(className).append(" {\n\n")
        sb.append("    @get:Rule\n")
        sb.append("    val composeTestRule = createComposeRule()\n\n")

        issues.forEachIndexed { index, issue ->
            sb.append("    @Test\n")
            sb.append("    fun test_").append(sanitizeIdentifier(issue.issueType)).append("_").append(index + 1).append("() {\n")
            val snippetLines = generateComposeSnippet(issue).lines()
            snippetLines.forEach { line ->
                sb.append("        ").append(line).append("\n")
            }
            sb.append("    }\n\n")
        }
        sb.append("}\n")
        return sb.toString()
    }

    private fun generateEspressoTestClass(
        sessionName: String,
        packageName: String,
        issues: List<ElementIssue>
    ): String {
        val className = sanitizeIdentifier(sessionName) + "AccessibilityEspressoTest"
        val sb = StringBuilder()
        sb.append("package ").append(packageName.ifEmpty { "com.example.app" }).append(".accessibility\n\n")
        sb.append("import androidx.test.espresso.Espresso.onView\n")
        sb.append("import androidx.test.espresso.assertion.ViewAssertions.matches\n")
        sb.append("import androidx.test.espresso.matcher.ViewMatchers.*\n")
        sb.append("import androidx.test.ext.junit.runners.AndroidJUnit4\n")
        sb.append("import org.hamcrest.Matchers.allOf\n")
        sb.append("import org.junit.Test\n")
        sb.append("import org.junit.runner.RunWith\n\n")
        sb.append("/**\n")
        sb.append(" * Automated Espresso Accessibility Regression Test\n")
        sb.append(" * Generated by AMASAMYA Accessibility Engine for session: ").append(sessionName).append("\n")
        sb.append(" */\n")
        sb.append("@RunWith(AndroidJUnit4::class)\n")
        sb.append("class ").append(className).append(" {\n\n")

        issues.forEachIndexed { index, issue ->
            sb.append("    @Test\n")
            sb.append("    fun test_").append(sanitizeIdentifier(issue.issueType)).append("_").append(index + 1).append("() {\n")
            val snippetLines = generateEspressoSnippet(issue).lines()
            snippetLines.forEach { line ->
                sb.append("        ").append(line).append("\n")
            }
            sb.append("    }\n\n")
        }
        sb.append("}\n")
        return sb.toString()
    }

    private fun generateComposeSnippet(issue: ElementIssue): String {
        val text = issue.text.ifEmpty { issue.contentDescription }
        val identifier = text.ifEmpty { issue.className.substringAfterLast('.') }
        return when (issue.issueType) {
            "Missing Label", "Labeling" -> """
                // Verify content description is assigned for screen readers (WCAG 1.1.1)
                composeTestRule
                    .onNodeWithContentDescription("${escapeString(identifier)}")
                    .assertIsDisplayed()
            """.trimIndent()

            "Target Size", "Touch Target" -> """
                // Verify minimum touch target dimensions meet 48dp threshold (WCAG 2.5.5 / 2.5.8)
                composeTestRule
                    .onNodeWithContentDescription("${escapeString(identifier)}")
                    .assertTouchTargetMinSize(48.dp)
            """.trimIndent()

            "Redundant Label", "Focus Noise" -> """
                // Verify element node is clear or correctly merged to avoid screen reader clutter
                composeTestRule
                    .onNodeWithText("${escapeString(identifier)}")
                    .assertIsDisplayed()
            """.trimIndent()

            else -> """
                // Accessibility assertion for ${issue.issueType} (${issue.wcagSc})
                composeTestRule
                    .onNodeWithContentDescription("${escapeString(identifier)}")
                    .assertIsDisplayed()
            """.trimIndent()
        }
    }

    private fun generateEspressoSnippet(issue: ElementIssue): String {
        val text = issue.text.ifEmpty { issue.contentDescription }
        val identifier = text.ifEmpty { issue.className.substringAfterLast('.') }
        return when (issue.issueType) {
            "Missing Label", "Labeling" -> """
                // Verify view has non-empty content description (WCAG 1.1.1)
                onView(withContentDescription("${escapeString(identifier)}"))
                    .check(matches(isDisplayed()))
            """.trimIndent()

            "Target Size", "Touch Target" -> """
                // Verify touch target is visible and meets minimum accessibility size (WCAG 2.5.5)
                onView(withContentDescription("${escapeString(identifier)}"))
                    .check(matches(isDisplayed()))
                    .check(matches(isClickable()))
            """.trimIndent()

            "Redundant Label", "Focus Noise" -> """
                // Verify view focusability and accessibility properties
                onView(withText("${escapeString(identifier)}"))
                    .check(matches(isDisplayed()))
            """.trimIndent()

            else -> """
                // Verify view is displayed and accessible (${issue.wcagSc})
                onView(withContentDescription("${escapeString(identifier)}"))
                    .check(matches(isDisplayed()))
            """.trimIndent()
        }
    }

    private fun sanitizeIdentifier(input: String): String {
        val sanitized = input.replace(Regex("[^a-zA-Z0-9]"), "")
        return if (sanitized.isEmpty()) "Screen" else sanitized.capitalize()
    }

    private fun escapeString(str: String): String {
        return str.replace("\\", "\\\\").replace("\"", "\\\"")
    }
}
