package com.example.amasamya.ui.views

import android.content.Intent
import android.net.Uri
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.heading
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.amasamya.theme.*

@Composable
fun LegalAndPrivacyDialog(
    initialTab: Int = 0, // 0: Privacy Policy, 1: Terms of Service
    onDismiss: () -> Unit
) {
    var selectedTab by remember { mutableIntStateOf(initialTab) }
    val scrollState = rememberScrollState()
    val context = LocalContext.current

    AlertDialog(
        onDismissRequest = onDismiss,
        containerColor = DeepSpace,
        titleContentColor = PureWhite,
        textContentColor = TextSecondary,
        title = {
            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text(
                    text = "Legal & Privacy Center",
                    fontWeight = FontWeight.Bold,
                    fontSize = 18.sp,
                    modifier = Modifier.semantics { heading() }
                )
                TabRow(
                    selectedTabIndex = selectedTab,
                    containerColor = DeepSpace,
                    contentColor = VibrantCyan
                ) {
                    Tab(
                        selected = selectedTab == 0,
                        onClick = { selectedTab = 0 },
                        text = { Text("Privacy Policy", fontWeight = FontWeight.Bold) }
                    )
                    Tab(
                        selected = selectedTab == 1,
                        onClick = { selectedTab = 1 },
                        text = { Text("Terms of Service", fontWeight = FontWeight.Bold) }
                    )
                }
            }
        },
        text = {
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .heightIn(max = 320.dp)
                    .clip(RoundedCornerShape(8.dp))
                    .background(GlassySurface)
                    .padding(12.dp)
                    .verticalScroll(scrollState)
            ) {
                if (selectedTab == 0) {
                    Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                        Text(
                            text = "AMASAMYA Privacy Policy",
                            fontWeight = FontWeight.Bold,
                            color = VibrantCyan,
                            fontSize = 15.sp
                        )
                        Text(
                            text = "Effective Date: January 1, 2026\nLast Updated: August 2026",
                            color = TextSecondary,
                            fontSize = 12.sp
                        )
                        Text(
                            text = "1. Zero Personal Data Collection: AMASAMYA operates 100% offline. We do not collect, transmit, store, or sell any personal data, audit history, app logs, or user credentials.",
                            color = PureWhite,
                            fontSize = 13.sp,
                            lineHeight = 18.sp
                        )
                        Text(
                            text = "2. Accessibility Service Permission: The Android Accessibility Service permission is utilized strictly on-device to inspect screen element bounds, text labels, and contrast ratios. No screen capture or keyboard data is recorded or uploaded.",
                            color = PureWhite,
                            fontSize = 13.sp,
                            lineHeight = 18.sp
                        )
                        Text(
                            text = "3. Local Report Exporters: All HTML, Markdown, and VPAT 2.4 reports generated by AMASAMYA remain stored exclusively in your device's private app storage.",
                            color = PureWhite,
                            fontSize = 13.sp,
                            lineHeight = 18.sp
                        )
                    }
                } else {
                    Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                        Text(
                            text = "AMASAMYA Terms of Service",
                            fontWeight = FontWeight.Bold,
                            color = VibrantCyan,
                            fontSize = 15.sp
                        )
                        Text(
                            text = "Effective Date: January 1, 2026",
                            color = TextSecondary,
                            fontSize = 12.sp
                        )
                        Text(
                            text = "1. Acceptance of Terms: By installing and using AMASAMYA, you agree to these terms. AMASAMYA is provided for accessibility auditing, automated testing, and developer compliance verification.",
                            color = PureWhite,
                            fontSize = 13.sp,
                            lineHeight = 18.sp
                        )
                        Text(
                            text = "2. License & Fair Usage: AMASAMYA grants you a non-exclusive, non-transferable license to perform digital accessibility audits on mobile applications.",
                            color = PureWhite,
                            fontSize = 13.sp,
                            lineHeight = 18.sp
                        )
                        Text(
                            text = "3. Compliance Disclaimer: Audit scores and VPAT reports generated by AMASAMYA provide automated testing insights against WCAG 2.2, GIGW 3.0, and IS 17802 standards and should be complemented by manual screen reader testing.",
                            color = PureWhite,
                            fontSize = 13.sp,
                            lineHeight = 18.sp
                        )
                    }
                }
            }
        },
        confirmButton = {
            Button(
                onClick = onDismiss,
                colors = ButtonDefaults.buttonColors(containerColor = VibrantCyan, contentColor = DeepSpace),
                shape = RoundedCornerShape(8.dp)
            ) {
                Text("Close", fontWeight = FontWeight.Bold)
            }
        },
        dismissButton = {
            TextButton(
                onClick = {
                    val url = if (selectedTab == 0) "https://amasamya.akhileshmalani.com/privacy.html" else "https://amasamya.akhileshmalani.com/terms.html"
                    val intent = Intent(Intent.ACTION_VIEW, Uri.parse(url))
                    context.startActivity(intent)
                }
            ) {
                Text("View Online 🌐", color = TextSecondary)
            }
        }
    )
}
